# Generated by Django 5.1.7 on 2025-04-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcousticCannon',
            fields=[
                ('cannon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wind_turbine_id', models.CharField(max_length=100)),
                ('installation_location', models.CharField(max_length=255)),
                ('last_lpg_charge_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('installation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BirdClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('bird_type_code', models.CharField(max_length=50)),
                ('bird_name_ko', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BirdMigrationCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_value', models.IntegerField(help_text='0: 철새, 1: 텃새')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BirdProtectionCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_value', models.IntegerField(help_text='0: 일반 새, 1: 보호종, 2: 천연기념물')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wind_turbine_id', models.CharField(max_length=100)),
                ('viewing_angle', models.FloatField()),
                ('installation_direction', models.CharField(max_length=50)),
                ('installation_height', models.FloatField()),
                ('rtsp_address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImportanceCode',
            fields=[
                ('importance_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('size_criteria_for_firing', models.CharField(max_length=255)),
                ('priority_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoundCode',
            fields=[
                ('sound_id', models.AutoField(primary_key=True, serialize=False)),
                ('sound_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wind_turbine_id', models.CharField(max_length=100)),
                ('installation_location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BirdAdditionalInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('habitat', models.CharField(max_length=255)),
                ('breeding_start_month', models.IntegerField()),
                ('breeding_end_month', models.IntegerField()),
                ('frequency_jan', models.FloatField()),
                ('frequency_feb', models.FloatField()),
                ('frequency_mar', models.FloatField()),
                ('frequency_apr', models.FloatField()),
                ('frequency_may', models.FloatField()),
                ('frequency_jun', models.FloatField()),
                ('frequency_jul', models.FloatField()),
                ('frequency_aug', models.FloatField()),
                ('frequency_sep', models.FloatField()),
                ('frequency_oct', models.FloatField()),
                ('frequency_nov', models.FloatField()),
                ('frequency_dec', models.FloatField()),
                ('bird_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.birdclass')),
            ],
        ),
        migrations.AddField(
            model_name='birdclass',
            name='migration_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camera.birdmigrationcode'),
        ),
        migrations.AddField(
            model_name='birdclass',
            name='protection_status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camera.birdprotectioncode'),
        ),
        migrations.CreateModel(
            name='DetectionInfo',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('bb_count', models.IntegerField()),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
        ),
        migrations.CreateModel(
            name='BBInfo',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('bb_left', models.FloatField()),
                ('bb_top', models.FloatField()),
                ('bb_right', models.FloatField()),
                ('bb_bottom', models.FloatField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.birdclass')),
                ('detection_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.detectioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='DeterrentRecord',
            fields=[
                ('deterrent_id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_distance', models.FloatField()),
                ('object_count', models.IntegerField()),
                ('deterrent_start_time', models.DateTimeField()),
                ('deterrent_end_time', models.DateTimeField()),
                ('cannon_firing_time', models.DateTimeField()),
                ('is_success', models.BooleanField()),
                ('cannon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.acousticcannon')),
                ('detection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.detectioninfo')),
                ('sound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.soundcode')),
                ('speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.speaker')),
            ],
        ),
    ]
