# Generated by Django 4.2.19 on 2025-03-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(default='소각시도', max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='현재 기온(°C)')),
                ('feels_like', models.FloatField(blank=True, null=True, verbose_name='체감 온도(°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='습도(%)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='풍속(m/s)')),
                ('wind_direction', models.CharField(blank=True, max_length=10, null=True, verbose_name='풍향')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='강수량(mm)')),
                ('precipitation_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='강수 형태')),
                ('air_quality', models.CharField(blank=True, max_length=20, null=True, verbose_name='대기질')),
                ('forecast_temperature', models.FloatField(blank=True, null=True, verbose_name='예보 기온(°C)')),
                ('forecast_humidity', models.FloatField(blank=True, null=True, verbose_name='예보 습도(%)')),
                ('forecast_wind_speed', models.FloatField(blank=True, null=True, verbose_name='예보 풍속(m/s)')),
                ('forecast_precipitation', models.FloatField(blank=True, null=True, verbose_name='예보 강수확률(%)')),
                ('forecast_air_quality', models.CharField(blank=True, max_length=20, null=True, verbose_name='예보 대기질')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '날씨 데이터',
                'verbose_name_plural': '날씨 데이터',
                'ordering': ['-timestamp'],
            },
        ),
    ]
