# Generated by Django 5.1.7 on 2025-05-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.FloatField(blank=True, null=True, verbose_name='시정(km)'),
        ),
    ]
